In [1]:
pip install pickle-mixin

  Created wheel for pickle-mixin: filename=pickle_mixin-1.0.2-py3-none-any.whl size=6008 sha256=f8801e21a5ba3c141a956cfba51dea09069abde9cdc1d6b3603a9dd35385f14e
  Stored in directory: /root/.cache/pip/wheels/d0/70/0b/673e09a7ed429660d22352a1b117b4f616a8fc054bdd7eb157
Successfully built pickle-mixin


In [2]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [3]:
df=pd.read_csv("homeprices.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [6]:
model=linear_model.LinearRegression()

model.fit(df[['area']],df.price)

LinearRegression()

In [7]:
model.intercept_

180616.43835616432

In [8]:
model.coef_

array([135.78767123])

In [10]:
model.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])

In [11]:
import pickle

In [18]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

In [19]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [20]:
mp.intercept_

180616.43835616432

In [21]:
mp.coef_

array([135.78767123])

In [22]:
mp.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])

# **JobLib**

In [24]:
pip install joblib

In [28]:
import joblib

In [29]:
joblib.dump(model, 'model_joblib')

['model_joblib']

In [30]:
mj = joblib.load('model_joblib')

In [32]:
mj.coef_

array([135.78767123])

In [33]:
mj.intercept_

180616.43835616432

In [34]:
mj.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])